version: '3'

services:
  ts-app:
    build: .
    container_name: ts-app
    entrypoint: .docker/entrypoint.sh
    environment:
      - DB_HOST=ts-db
      - DB_DATABASE=transacao-simplificada
      - DB_USERNAME=root
      - DB_PASSWORD=123456
    volumes:
      - .:/var/www
    networks:
      - ts-app-network
    depends_on:
      - ts-db

  ts-nginx:
    build: .docker/nginx
    container_name: ts-nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - ts-app-network
    depends_on:
      - ts-app

  ts-db:
    build: .docker/mariadb
    container_name: ts-db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=transacao-simplificada
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
    networks:
      - ts-app-network

  # ts-redis:
  #   image: redis:alpine
  #   expose:
  #     - 6379
  #   networks:
  #     - ts-app-network

networks:
  ts-app-network:
    driver: bridge
